version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'buckyworld_db'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'buckymon'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    image: spring-boot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/buckyworld_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: buckymon
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
volumes:
  db-data:
